console.log("Update from A")
console.log("Update from feature branch")
console.log("Feature FF")
console.log("Feature NO-FF")
 console.log("Squash 1")
 console.log("Squash 2")
 console.log("Squash 2")
